//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourRowClient.FourRowServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDoesntExistsFault", Namespace="http://schemas.datacontract.org/2004/07/WcfFourRowService")]
    [System.SerializableAttribute()]
    public partial class UserDoesntExistsFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WrongPasswordFault", Namespace="http://schemas.datacontract.org/2004/07/WcfFourRowService")]
    [System.SerializableAttribute()]
    public partial class WrongPasswordFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserExistsFault", Namespace="http://schemas.datacontract.org/2004/07/WcfFourRowService")]
    [System.SerializableAttribute()]
    public partial class UserExistsFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAlreadyConnectedFault", Namespace="http://schemas.datacontract.org/2004/07/WcfFourRowService")]
    [System.SerializableAttribute()]
    public partial class UserAlreadyConnectedFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MoveResult", Namespace="http://schemas.datacontract.org/2004/07/WcfFourRowService")]
    public enum MoveResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YouWon = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YouLose = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Draw = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotYourTurn = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameOn = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nothing = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IllegalMove = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FourRowServiceReference.IFourRowService", CallbackContract=typeof(FourRowClient.FourRowServiceReference.IFourRowServiceCallback))]
    public interface IFourRowService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/ClientConnected", ReplyAction="http://tempuri.org/IFourRowService/ClientConnectedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Data.Common.DbException), Action="http://tempuri.org/IFourRowService/ClientConnectedDbExceptionFault", Name="DbException", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(FourRowClient.FourRowServiceReference.UserDoesntExistsFault), Action="http://tempuri.org/IFourRowService/ClientConnectedUserDoesntExistsFaultFault", Name="UserDoesntExistsFault", Namespace="http://schemas.datacontract.org/2004/07/WcfFourRowService")]
        [System.ServiceModel.FaultContractAttribute(typeof(FourRowClient.FourRowServiceReference.WrongPasswordFault), Action="http://tempuri.org/IFourRowService/ClientConnectedWrongPasswordFaultFault", Name="WrongPasswordFault", Namespace="http://schemas.datacontract.org/2004/07/WcfFourRowService")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/ClientConnectedExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        void ClientConnected(string userName, string hashedPasswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/ClientConnected", ReplyAction="http://tempuri.org/IFourRowService/ClientConnectedResponse")]
        System.Threading.Tasks.Task ClientConnectedAsync(string userName, string hashedPasswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/ClientRegistered", ReplyAction="http://tempuri.org/IFourRowService/ClientRegisteredResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Data.Common.DbException), Action="http://tempuri.org/IFourRowService/ClientRegisteredDbExceptionFault", Name="DbException", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(FourRowClient.FourRowServiceReference.UserExistsFault), Action="http://tempuri.org/IFourRowService/ClientRegisteredUserExistsFaultFault", Name="UserExistsFault", Namespace="http://schemas.datacontract.org/2004/07/WcfFourRowService")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/ClientRegisteredExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        void ClientRegistered(string userName, string hashedPasswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/ClientRegistered", ReplyAction="http://tempuri.org/IFourRowService/ClientRegisteredResponse")]
        System.Threading.Tasks.Task ClientRegisteredAsync(string userName, string hashedPasswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/ClientDisconnected", ReplyAction="http://tempuri.org/IFourRowService/ClientDisconnectedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/ClientDisconnectedExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        [System.ServiceModel.FaultContractAttribute(typeof(FourRowClient.FourRowServiceReference.UserAlreadyConnectedFault), Action="http://tempuri.org/IFourRowService/ClientDisconnectedUserAlreadyConnectedFaultFau" +
            "lt", Name="UserAlreadyConnectedFault", Namespace="http://schemas.datacontract.org/2004/07/WcfFourRowService")]
        void ClientDisconnected(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/ClientDisconnected", ReplyAction="http://tempuri.org/IFourRowService/ClientDisconnectedResponse")]
        System.Threading.Tasks.Task ClientDisconnectedAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/ClientDisconnectedBeforeGame", ReplyAction="http://tempuri.org/IFourRowService/ClientDisconnectedBeforeGameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/ClientDisconnectedBeforeGameExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        void ClientDisconnectedBeforeGame(string userName, string opponent, string whosOut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/ClientDisconnectedBeforeGame", ReplyAction="http://tempuri.org/IFourRowService/ClientDisconnectedBeforeGameResponse")]
        System.Threading.Tasks.Task ClientDisconnectedBeforeGameAsync(string userName, string opponent, string whosOut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/ClientDisconnectedThrowGame", ReplyAction="http://tempuri.org/IFourRowService/ClientDisconnectedThrowGameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Data.Common.DbException), Action="http://tempuri.org/IFourRowService/ClientDisconnectedThrowGameDbExceptionFault", Name="DbException", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/ClientDisconnectedThrowGameExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        void ClientDisconnectedThrowGame(string currentPlayer, string opponent, string whosOut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/ClientDisconnectedThrowGame", ReplyAction="http://tempuri.org/IFourRowService/ClientDisconnectedThrowGameResponse")]
        System.Threading.Tasks.Task ClientDisconnectedThrowGameAsync(string currentPlayer, string opponent, string whosOut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/WantToPlayWithClient", ReplyAction="http://tempuri.org/IFourRowService/WantToPlayWithClientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/WantToPlayWithClientExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        void WantToPlayWithClient(string currentPlayer, string opponent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/WantToPlayWithClient", ReplyAction="http://tempuri.org/IFourRowService/WantToPlayWithClientResponse")]
        System.Threading.Tasks.Task WantToPlayWithClientAsync(string currentPlayer, string opponent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/OpponentAcceptToPlay", ReplyAction="http://tempuri.org/IFourRowService/OpponentAcceptToPlayResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Data.Common.DbException), Action="http://tempuri.org/IFourRowService/OpponentAcceptToPlayDbExceptionFault", Name="DbException", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/OpponentAcceptToPlayExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        void OpponentAcceptToPlay(string currentPlayer, string opponent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/OpponentAcceptToPlay", ReplyAction="http://tempuri.org/IFourRowService/OpponentAcceptToPlayResponse")]
        System.Threading.Tasks.Task OpponentAcceptToPlayAsync(string currentPlayer, string opponent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/OpponentDeclineToPlay", ReplyAction="http://tempuri.org/IFourRowService/OpponentDeclineToPlayResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/OpponentDeclineToPlayExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        void OpponentDeclineToPlay(string currentPlayer, string opponent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/OpponentDeclineToPlay", ReplyAction="http://tempuri.org/IFourRowService/OpponentDeclineToPlayResponse")]
        System.Threading.Tasks.Task OpponentDeclineToPlayAsync(string currentPlayer, string opponent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetClientsThatNotPlayNow", ReplyAction="http://tempuri.org/IFourRowService/GetClientsThatNotPlayNowResponse")]
        System.Collections.Generic.List<string> GetClientsThatNotPlayNow();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetClientsThatNotPlayNow", ReplyAction="http://tempuri.org/IFourRowService/GetClientsThatNotPlayNowResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetClientsThatNotPlayNowAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistory", ReplyAction="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Data.Common.DbException), Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryDbExceptionFault", Name="DbException", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Collections.Generic.List<string> GetAllUsersGamesHistory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistory", ReplyAction="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAllUsersGamesHistoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetAllUsersInDb", ReplyAction="http://tempuri.org/IFourRowService/GetAllUsersInDbResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Data.Common.DbException), Action="http://tempuri.org/IFourRowService/GetAllUsersInDbDbExceptionFault", Name="DbException", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/GetAllUsersInDbExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Collections.Generic.List<string> GetAllUsersInDb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetAllUsersInDb", ReplyAction="http://tempuri.org/IFourRowService/GetAllUsersInDbResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAllUsersInDbAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByName", ReplyAction="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Data.Common.DbException), Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByNameDbExceptio" +
            "nFault", Name="DbException", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByNameExceptionF" +
            "ault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Collections.Generic.List<string> GetAllUsersGamesHistoryOrderedByName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByName", ReplyAction="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByNameResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAllUsersGamesHistoryOrderedByNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByGames", ReplyAction="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByGamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Data.Common.DbException), Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByGamesDbExcepti" +
            "onFault", Name="DbException", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByGamesException" +
            "Fault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Collections.Generic.List<string> GetAllUsersGamesHistoryOrderedByGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByGames", ReplyAction="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByGamesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAllUsersGamesHistoryOrderedByGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByWins", ReplyAction="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByWinsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Data.Common.DbException), Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByWinsDbExceptio" +
            "nFault", Name="DbException", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByWinsExceptionF" +
            "ault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Collections.Generic.List<string> GetAllUsersGamesHistoryOrderedByWins();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByWins", ReplyAction="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByWinsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAllUsersGamesHistoryOrderedByWinsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByLoses", ReplyAction="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByLosesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Data.Common.DbException), Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByLosesDbExcepti" +
            "onFault", Name="DbException", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByLosesException" +
            "Fault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Collections.Generic.List<string> GetAllUsersGamesHistoryOrderedByLoses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByLoses", ReplyAction="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByLosesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAllUsersGamesHistoryOrderedByLosesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByPoints", ReplyAction="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByPointsResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Data.Common.DbException), Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByPointsDbExcept" +
            "ionFault", Name="DbException", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByPointsExceptio" +
            "nFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Collections.Generic.List<string> GetAllUsersGamesHistoryOrderedByPoints();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByPoints", ReplyAction="http://tempuri.org/IFourRowService/GetAllUsersGamesHistoryOrderedByPointsResponse" +
            "")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAllUsersGamesHistoryOrderedByPointsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/AllTheGamesThatPlayesSoFar", ReplyAction="http://tempuri.org/IFourRowService/AllTheGamesThatPlayesSoFarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Data.Common.DbException), Action="http://tempuri.org/IFourRowService/AllTheGamesThatPlayesSoFarDbExceptionFault", Name="DbException", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/AllTheGamesThatPlayesSoFarExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Collections.Generic.List<string> AllTheGamesThatPlayesSoFar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/AllTheGamesThatPlayesSoFar", ReplyAction="http://tempuri.org/IFourRowService/AllTheGamesThatPlayesSoFarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> AllTheGamesThatPlayesSoFarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/AllTheGamesThatPlayesNow", ReplyAction="http://tempuri.org/IFourRowService/AllTheGamesThatPlayesNowResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Data.Common.DbException), Action="http://tempuri.org/IFourRowService/AllTheGamesThatPlayesNowDbExceptionFault", Name="DbException", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/AllTheGamesThatPlayesNowExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Collections.Generic.List<string> AllTheGamesThatPlayesNow();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/AllTheGamesThatPlayesNow", ReplyAction="http://tempuri.org/IFourRowService/AllTheGamesThatPlayesNowResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> AllTheGamesThatPlayesNowAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/AllTheGamesBetweenTwoClients", ReplyAction="http://tempuri.org/IFourRowService/AllTheGamesBetweenTwoClientsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Data.Common.DbException), Action="http://tempuri.org/IFourRowService/AllTheGamesBetweenTwoClientsDbExceptionFault", Name="DbException", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/AllTheGamesBetweenTwoClientsExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Collections.Generic.List<string> AllTheGamesBetweenTwoClients(string userName1, string userName2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/AllTheGamesBetweenTwoClients", ReplyAction="http://tempuri.org/IFourRowService/AllTheGamesBetweenTwoClientsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> AllTheGamesBetweenTwoClientsAsync(string userName1, string userName2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/AllTheGamesOfSomeClient", ReplyAction="http://tempuri.org/IFourRowService/AllTheGamesOfSomeClientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Data.Common.DbException), Action="http://tempuri.org/IFourRowService/AllTheGamesOfSomeClientDbExceptionFault", Name="DbException", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/AllTheGamesOfSomeClientExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Collections.Generic.List<string> AllTheGamesOfSomeClient(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/AllTheGamesOfSomeClient", ReplyAction="http://tempuri.org/IFourRowService/AllTheGamesOfSomeClientResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> AllTheGamesOfSomeClientAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/ReportMove", ReplyAction="http://tempuri.org/IFourRowService/ReportMoveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Data.Common.DbException), Action="http://tempuri.org/IFourRowService/ReportMoveDbExceptionFault", Name="DbException", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/ReportMoveExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Tuple<FourRowClient.FourRowServiceReference.MoveResult, int> ReportMove(string currentPlayer, string opponent, string whoMoved, int location, double pointX, double pointY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/ReportMove", ReplyAction="http://tempuri.org/IFourRowService/ReportMoveResponse")]
        System.Threading.Tasks.Task<System.Tuple<FourRowClient.FourRowServiceReference.MoveResult, int>> ReportMoveAsync(string currentPlayer, string opponent, string whoMoved, int location, double pointX, double pointY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetMeBackToWaitingList", ReplyAction="http://tempuri.org/IFourRowService/GetMeBackToWaitingListResponse")]
        void GetMeBackToWaitingList(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetMeBackToWaitingList", ReplyAction="http://tempuri.org/IFourRowService/GetMeBackToWaitingListResponse")]
        System.Threading.Tasks.Task GetMeBackToWaitingListAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetMyPos", ReplyAction="http://tempuri.org/IFourRowService/GetMyPosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/GetMyPosExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        int GetMyPos(string currentPlayer, string opponent, string whoWantIt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/GetMyPos", ReplyAction="http://tempuri.org/IFourRowService/GetMyPosResponse")]
        System.Threading.Tasks.Task<int> GetMyPosAsync(string currentPlayer, string opponent, string whoWantIt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/SetMyPos", ReplyAction="http://tempuri.org/IFourRowService/SetMyPosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/SetMyPosExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        void SetMyPos(string currentPlayer, string opponent, string whoWantIt, int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/SetMyPos", ReplyAction="http://tempuri.org/IFourRowService/SetMyPosResponse")]
        System.Threading.Tasks.Task SetMyPosAsync(string currentPlayer, string opponent, string whoWantIt, int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/KillTheGame", ReplyAction="http://tempuri.org/IFourRowService/KillTheGameResponse")]
        void KillTheGame(string currentPlayer, string opponent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/KillTheGame", ReplyAction="http://tempuri.org/IFourRowService/KillTheGameResponse")]
        System.Threading.Tasks.Task KillTheGameAsync(string currentPlayer, string opponent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/ClearUsers", ReplyAction="http://tempuri.org/IFourRowService/ClearUsersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Data.Common.DbException), Action="http://tempuri.org/IFourRowService/ClearUsersDbExceptionFault", Name="DbException", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IFourRowService/ClearUsersExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool ClearUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/ClearUsers", ReplyAction="http://tempuri.org/IFourRowService/ClearUsersResponse")]
        System.Threading.Tasks.Task<bool> ClearUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/Ping", ReplyAction="http://tempuri.org/IFourRowService/PingResponse")]
        bool Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/Ping", ReplyAction="http://tempuri.org/IFourRowService/PingResponse")]
        System.Threading.Tasks.Task<bool> PingAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFourRowServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFourRowService/OtherPlayerMoved")]
        void OtherPlayerMoved(System.Tuple<FourRowClient.FourRowServiceReference.MoveResult, int> moveResult, double pointX, double pointY);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFourRowService/NotifyOpponentChallenge")]
        void NotifyOpponentChallenge(string currentPlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFourRowService/HeyOpponentDeclineToPlay")]
        void HeyOpponentDeclineToPlay();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFourRowService/OpponentAcceptToPlayLetsStart")]
        void OpponentAcceptToPlayLetsStart();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFourRowService/LetsStart")]
        void LetsStart();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFourRowService/OpponentDisconnectedBeforeTheGame")]
        void OpponentDisconnectedBeforeTheGame();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFourRowService/OpponentDisconnectedThrowGameYouWon")]
        void OpponentDisconnectedThrowGameYouWon();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFourRowServiceChannel : FourRowClient.FourRowServiceReference.IFourRowService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FourRowServiceClient : System.ServiceModel.DuplexClientBase<FourRowClient.FourRowServiceReference.IFourRowService>, FourRowClient.FourRowServiceReference.IFourRowService {
        
        public FourRowServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public FourRowServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public FourRowServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FourRowServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FourRowServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ClientConnected(string userName, string hashedPasswd) {
            base.Channel.ClientConnected(userName, hashedPasswd);
        }
        
        public System.Threading.Tasks.Task ClientConnectedAsync(string userName, string hashedPasswd) {
            return base.Channel.ClientConnectedAsync(userName, hashedPasswd);
        }
        
        public void ClientRegistered(string userName, string hashedPasswd) {
            base.Channel.ClientRegistered(userName, hashedPasswd);
        }
        
        public System.Threading.Tasks.Task ClientRegisteredAsync(string userName, string hashedPasswd) {
            return base.Channel.ClientRegisteredAsync(userName, hashedPasswd);
        }
        
        public void ClientDisconnected(string userName) {
            base.Channel.ClientDisconnected(userName);
        }
        
        public System.Threading.Tasks.Task ClientDisconnectedAsync(string userName) {
            return base.Channel.ClientDisconnectedAsync(userName);
        }
        
        public void ClientDisconnectedBeforeGame(string userName, string opponent, string whosOut) {
            base.Channel.ClientDisconnectedBeforeGame(userName, opponent, whosOut);
        }
        
        public System.Threading.Tasks.Task ClientDisconnectedBeforeGameAsync(string userName, string opponent, string whosOut) {
            return base.Channel.ClientDisconnectedBeforeGameAsync(userName, opponent, whosOut);
        }
        
        public void ClientDisconnectedThrowGame(string currentPlayer, string opponent, string whosOut) {
            base.Channel.ClientDisconnectedThrowGame(currentPlayer, opponent, whosOut);
        }
        
        public System.Threading.Tasks.Task ClientDisconnectedThrowGameAsync(string currentPlayer, string opponent, string whosOut) {
            return base.Channel.ClientDisconnectedThrowGameAsync(currentPlayer, opponent, whosOut);
        }
        
        public void WantToPlayWithClient(string currentPlayer, string opponent) {
            base.Channel.WantToPlayWithClient(currentPlayer, opponent);
        }
        
        public System.Threading.Tasks.Task WantToPlayWithClientAsync(string currentPlayer, string opponent) {
            return base.Channel.WantToPlayWithClientAsync(currentPlayer, opponent);
        }
        
        public void OpponentAcceptToPlay(string currentPlayer, string opponent) {
            base.Channel.OpponentAcceptToPlay(currentPlayer, opponent);
        }
        
        public System.Threading.Tasks.Task OpponentAcceptToPlayAsync(string currentPlayer, string opponent) {
            return base.Channel.OpponentAcceptToPlayAsync(currentPlayer, opponent);
        }
        
        public void OpponentDeclineToPlay(string currentPlayer, string opponent) {
            base.Channel.OpponentDeclineToPlay(currentPlayer, opponent);
        }
        
        public System.Threading.Tasks.Task OpponentDeclineToPlayAsync(string currentPlayer, string opponent) {
            return base.Channel.OpponentDeclineToPlayAsync(currentPlayer, opponent);
        }
        
        public System.Collections.Generic.List<string> GetClientsThatNotPlayNow() {
            return base.Channel.GetClientsThatNotPlayNow();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetClientsThatNotPlayNowAsync() {
            return base.Channel.GetClientsThatNotPlayNowAsync();
        }
        
        public System.Collections.Generic.List<string> GetAllUsersGamesHistory() {
            return base.Channel.GetAllUsersGamesHistory();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAllUsersGamesHistoryAsync() {
            return base.Channel.GetAllUsersGamesHistoryAsync();
        }
        
        public System.Collections.Generic.List<string> GetAllUsersInDb() {
            return base.Channel.GetAllUsersInDb();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAllUsersInDbAsync() {
            return base.Channel.GetAllUsersInDbAsync();
        }
        
        public System.Collections.Generic.List<string> GetAllUsersGamesHistoryOrderedByName() {
            return base.Channel.GetAllUsersGamesHistoryOrderedByName();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAllUsersGamesHistoryOrderedByNameAsync() {
            return base.Channel.GetAllUsersGamesHistoryOrderedByNameAsync();
        }
        
        public System.Collections.Generic.List<string> GetAllUsersGamesHistoryOrderedByGames() {
            return base.Channel.GetAllUsersGamesHistoryOrderedByGames();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAllUsersGamesHistoryOrderedByGamesAsync() {
            return base.Channel.GetAllUsersGamesHistoryOrderedByGamesAsync();
        }
        
        public System.Collections.Generic.List<string> GetAllUsersGamesHistoryOrderedByWins() {
            return base.Channel.GetAllUsersGamesHistoryOrderedByWins();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAllUsersGamesHistoryOrderedByWinsAsync() {
            return base.Channel.GetAllUsersGamesHistoryOrderedByWinsAsync();
        }
        
        public System.Collections.Generic.List<string> GetAllUsersGamesHistoryOrderedByLoses() {
            return base.Channel.GetAllUsersGamesHistoryOrderedByLoses();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAllUsersGamesHistoryOrderedByLosesAsync() {
            return base.Channel.GetAllUsersGamesHistoryOrderedByLosesAsync();
        }
        
        public System.Collections.Generic.List<string> GetAllUsersGamesHistoryOrderedByPoints() {
            return base.Channel.GetAllUsersGamesHistoryOrderedByPoints();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAllUsersGamesHistoryOrderedByPointsAsync() {
            return base.Channel.GetAllUsersGamesHistoryOrderedByPointsAsync();
        }
        
        public System.Collections.Generic.List<string> AllTheGamesThatPlayesSoFar() {
            return base.Channel.AllTheGamesThatPlayesSoFar();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> AllTheGamesThatPlayesSoFarAsync() {
            return base.Channel.AllTheGamesThatPlayesSoFarAsync();
        }
        
        public System.Collections.Generic.List<string> AllTheGamesThatPlayesNow() {
            return base.Channel.AllTheGamesThatPlayesNow();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> AllTheGamesThatPlayesNowAsync() {
            return base.Channel.AllTheGamesThatPlayesNowAsync();
        }
        
        public System.Collections.Generic.List<string> AllTheGamesBetweenTwoClients(string userName1, string userName2) {
            return base.Channel.AllTheGamesBetweenTwoClients(userName1, userName2);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> AllTheGamesBetweenTwoClientsAsync(string userName1, string userName2) {
            return base.Channel.AllTheGamesBetweenTwoClientsAsync(userName1, userName2);
        }
        
        public System.Collections.Generic.List<string> AllTheGamesOfSomeClient(string userName) {
            return base.Channel.AllTheGamesOfSomeClient(userName);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> AllTheGamesOfSomeClientAsync(string userName) {
            return base.Channel.AllTheGamesOfSomeClientAsync(userName);
        }
        
        public System.Tuple<FourRowClient.FourRowServiceReference.MoveResult, int> ReportMove(string currentPlayer, string opponent, string whoMoved, int location, double pointX, double pointY) {
            return base.Channel.ReportMove(currentPlayer, opponent, whoMoved, location, pointX, pointY);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<FourRowClient.FourRowServiceReference.MoveResult, int>> ReportMoveAsync(string currentPlayer, string opponent, string whoMoved, int location, double pointX, double pointY) {
            return base.Channel.ReportMoveAsync(currentPlayer, opponent, whoMoved, location, pointX, pointY);
        }
        
        public void GetMeBackToWaitingList(string userName) {
            base.Channel.GetMeBackToWaitingList(userName);
        }
        
        public System.Threading.Tasks.Task GetMeBackToWaitingListAsync(string userName) {
            return base.Channel.GetMeBackToWaitingListAsync(userName);
        }
        
        public int GetMyPos(string currentPlayer, string opponent, string whoWantIt) {
            return base.Channel.GetMyPos(currentPlayer, opponent, whoWantIt);
        }
        
        public System.Threading.Tasks.Task<int> GetMyPosAsync(string currentPlayer, string opponent, string whoWantIt) {
            return base.Channel.GetMyPosAsync(currentPlayer, opponent, whoWantIt);
        }
        
        public void SetMyPos(string currentPlayer, string opponent, string whoWantIt, int pos) {
            base.Channel.SetMyPos(currentPlayer, opponent, whoWantIt, pos);
        }
        
        public System.Threading.Tasks.Task SetMyPosAsync(string currentPlayer, string opponent, string whoWantIt, int pos) {
            return base.Channel.SetMyPosAsync(currentPlayer, opponent, whoWantIt, pos);
        }
        
        public void KillTheGame(string currentPlayer, string opponent) {
            base.Channel.KillTheGame(currentPlayer, opponent);
        }
        
        public System.Threading.Tasks.Task KillTheGameAsync(string currentPlayer, string opponent) {
            return base.Channel.KillTheGameAsync(currentPlayer, opponent);
        }
        
        public bool ClearUsers() {
            return base.Channel.ClearUsers();
        }
        
        public System.Threading.Tasks.Task<bool> ClearUsersAsync() {
            return base.Channel.ClearUsersAsync();
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<bool> PingAsync() {
            return base.Channel.PingAsync();
        }
    }
}
