//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfFourRowService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameDetail
    {
        public int GameId { get; set; }
        public string User1Name { get; set; }
        public string User2Name { get; set; }
        public string WinningUserName { get; set; }
        public int PointsUser1 { get; set; }
        public int PointsUser2 { get; set; }
        public System.DateTime GameDateStart { get; set; }
        public System.DateTime GameDateEnd { get; set; }
    }
}
