//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfFourRowService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FourinrowDBContext : DbContext
    {
        public FourinrowDBContext()
            : base("name=fourinrowDB_shay_shalevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GameDetail> GameDetails { get; set; }
        public virtual DbSet<GameDetailsNow> GameDetailsNows { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
