//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourRowClient.FourRowServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FourRowServiceReference.IFourRowService")]
    public interface IFourRowService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/lala", ReplyAction="http://tempuri.org/IFourRowService/lalaResponse")]
        void lala();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFourRowService/lala", ReplyAction="http://tempuri.org/IFourRowService/lalaResponse")]
        System.Threading.Tasks.Task lalaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFourRowServiceChannel : FourRowClient.FourRowServiceReference.IFourRowService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FourRowServiceClient : System.ServiceModel.ClientBase<FourRowClient.FourRowServiceReference.IFourRowService>, FourRowClient.FourRowServiceReference.IFourRowService {
        
        public FourRowServiceClient() {
        }
        
        public FourRowServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FourRowServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FourRowServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FourRowServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void lala() {
            base.Channel.lala();
        }
        
        public System.Threading.Tasks.Task lalaAsync() {
            return base.Channel.lalaAsync();
        }
    }
}
